{
    "__fails__": true,
    "__exception__": {
        "message": "I was programmed to fail"
    },
    "__records__": [
        {
            "message": "I'm about to fail!",
            "levelname": "WARNING"
        },
        {
            "message": "Failing..",
            "levelname": "ERROR"
        }
    ],

    "data": {
        "families": ["family1"],
        "order": 2,
        "canProcessInstance": true
    }
}